<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [2]:
# Subsetting means to ‘select’.
# Indexing refers to selecting one element.
# Slicing refers to selecting a range of elements.

### slicing
### [x,y,z] -- x is start (inclusive), y is end (exclusive), z is number of steps taken
### a blank x or y suggests everything from the beginning/to the end
### a negative number (x) suggests choosing element from the back
### -1 step means giving elements in reverse order

Syntax	| Result		| Note
|:------|:-------------:|:-------|
x[0]	|First element	|'a1'	
x[-1]	|Last element	|'j10'	
x[0:3]	|Index 0 to 2	|['a1','b2','c3']	Gives 
 elements
x[1:6]	|Index 1 to 5	|['b2','c3','d4','e5','f6']	Gives 
 elements
x[1:6:2]	|Index 1 to 5 in steps of 2	|['b2','d4','f6']	Gives every other of 
 elements
x[5:]	|Index 5 to the end	|['f6','g7','h8','i9','j10']	Gives len(x)
 elements
x[:5]	|Index 0 to 5	|['a1','b2','c3','d4','e5']	Gives 
 elements
x[5:2:-1]	|Index 5 to 3 (i.e., in reverse)	|['f6','e5','d4']	Gives 
 elements
x[::-1]	|Reverses the list	|['j10','i9','h8',...,'b2','a1']	

## 1.2 Arrays only | Subsetting by masking

In [6]:
import numpy as np
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3 # using a condition to select a range you want
my_mask # python wiill process this as a tue or false array

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [7]:
np_array[my_mask] # putting my_mask in an array will print out elements within the condition
# count-true counts number of "trues"

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [9]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [11]:
py_list_2d[3]
np_array_2d[3] #position 4,,index 3

array(['4', 'D'], dtype='<U11')

In [14]:
py_list_2d[3][0] # indicates the index + element placement
np_array_2d[3, 0] # first element @ position 4

'4'

In [15]:
py_list_2d[:3][0]
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U11')

In [20]:
py_list_2d[3:6][0]
# doing this in normal list gives the first position within this range of positions

[4, 'D']

In [21]:
np_array_2d[3:6, 0]
# doing this in numpy array gives the first elements from within this range of positions

array(['4', '5', '6'], dtype='<U11')

## 1.4 Growing lists

In [22]:
# appending in lists
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [28]:
x = [1, 2, 3] 
x += [4, 5, 6]
x
x=[1, 2, 3] # appending lists -- literally adding everything within the curly brackets
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

In [29]:
x=[1, 2, 3] # extending lists
x.extend([4, 5, 6]) # only adds on the numbers
x

[1, 2, 3, 4, 5, 6]

# Some loose ends

## 1.5 Tuples

In [31]:
# tuples are defined within curly brackets
a=(1, 2, 3)     # Define tuple
type(a)

tuple

In [32]:
print(a[0])    # Access data

1


In [33]:
# tuples are immutable and cannot be changed
# useful when very long codes are involved

## 1.6 Be VERY careful when copying

In [36]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!
# this directly changes the original list if you plan to change something

In [39]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()
# this makes y and z lists but NOT a tuple -- components of x can be changed without changing the actual x

## Footnotes