<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

In [1]:
py_fruits_list = ["banana", "apple", "orange", "pear", "grapes"]
py_animals_list = ["chicken", "noob", "donkey", "cat", "dog"]
#python list

'dog'

In [5]:
import numpy as np
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])
#numpy array and lists, can be identified by index
# 

In [6]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}
# dictionary -- uses key and associate with value, separated by :
# only requires one structure to hold information that associates a value to another key

## 1.1 Let’s compare

## 1.2 Accessing data from a list (or array)

In [7]:
py_animals_list[4]

'dog'

## 1.3 Accessing data from a dictionary

In [10]:
superhero_info.keys() #keys belonging to the superhero info was extracted

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [11]:
superhero_info.values() #values belonging to the superhero info was extracted

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

In [12]:
superhero_info["Natasha Romanoff"] #extracting value from key

'Black Widow'

## 1.4 Higher dimensional lists

In [13]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]
# 2d array (one "key" and one "value" in each bracket)

# 2 Lists vs. Arrays

## 2.1 Size

In [14]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [17]:
len(py_list_2d)

10

In [19]:
len(np_array_2d)

10

In [21]:
np_array_2d.shape #tells size + # of elements in each set(?)

(10, 2)

## 2.2 Arrays are fussy about type

In [23]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

py_list

[1, 1.5, 'A']

In [28]:
type(py_list) #treats everyone as a string by having ""

list

In [25]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

In [30]:
type(np_array) #only accept one type of data (str, int, float)
#to change type -- use astype()

numpy.ndarray

## 2.3 Adding a number

In [32]:
# lists cannot add number
# arrays can

## 2.4 Adding another list

In [33]:
# lists only add elements add the new numbers at the back of each other (sorta like append)

In [34]:
#array adds the elements together depending on position

## 2.5 Multiplying by a Number

In [36]:
# lists only add elements of the same list add the back of the original (sorta like append)
py_list = [1, 2, 3, 4, 5]
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [37]:
#array actually multiplies the elements
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list) 
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [40]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
np_array**2 #squares work

array([ 1,  4,  9, 16, 25])

In [39]:
py_list**2 #won't work

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## 2.7 Asking questions

In [41]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list) 

In [43]:
np_array > 3  

array([False, False, False,  True,  True])

In [46]:
py_list == 3     # Works, but what IS the question?
# is it asking to check if all elements are = to 3?

False

In [45]:
np_array == 3  

array([False, False,  True, False, False])

## 2.8 Mathematics

In [50]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)  
sum(py_list)     # sum() is a base Python function

15

In [51]:
max(py_list)     # max() is a base Python function

5

In [58]:
min(py_list)      # min() is a base Python function

1

In [59]:
np_array.sum()

15

In [60]:
np_array.std()

1.4142135623730951

In [62]:
py_list.std() #standard deviation non existent for python list

AttributeError: 'list' object has no attribute 'std'

# Exercises & Self-Assessment

In [26]:
import os

In [25]:
import scipy

ModuleNotFoundError: No module named 'scipy'

In [ ]:



# Your solution here




## Footnotes